### ISSUE TITLE
Make bar smaller (or adjustable)

### ISSUE THREAD

**Issue by merrill-oakland** [CatalystIT-AU/moodle-local_envbar#2]
I really like this plugin, but we would like to the bar to be a bit shorter (less white space above and below the words). Because of how the styles are applied, it's harder to override in our custom styles.

It would be nice if it was: a) smaller, b) a setting, c) overridable.

The last one could be done by getting rid of !important. I assume you added it because the default one would override, but you just need a higher scoring selector, like ``header.nabvar-fixed-top``, ``.navbar.nabvar-fixed-top``, or ``body .nabvar-fixed-top``.

**Comment by brendanheywood** [comment]
@suankan lets aim for c) so remove the need for the !important

**Comment by suankan** [comment]
I'm looking into this.

**Comment by brendanheywood** [comment]
Thanks for the feedback @merrill-oakland :)

**Comment by brendanheywood** [comment]
We are also going to make this a config item so it can be directly tweaked without resorting to modifying the theme css at all, see #13
