### ISSUE TITLE
Envbar doesn't show on the login page (doesn't call the navigation extend callback)

### ISSUE THREAD

**Issue by douglasedmunds** [CatalystIT-AU/moodle-local_envbar#23]
Updating the 'Text to show' string doesn't take effect on the login page.
Once logged in the correct 'Text to show' is displayed.
Clearing all caches hasn't changed it either.

Steps:
1. Set string
2. Logout
3. Login
4. Change string
5. Check updated on current page
6. Logout, old string displayed.

**Comment by brendanheywood** [comment]
Yes I've come across this too, the login page doesn't trigger the same hook as other pages and so the whole logic never runs. I need to think about this some more, it may even require changing the plugin type to an auth plugin which would be a pain but also have some other advantages.

**Comment by brendanheywood** [comment]
I have fixed this, but in order to do so I've had to create a whole new plugin because not all hooks are available to all plugin types. Please install this new plugin:

https://github.com/catalyst/moodle-auth_envbar
