### ISSUE TITLE
Add a class to the body when enabled

### ISSUE THREAD

**Issue by meepster-nz** [CatalystIT-AU/moodle-local_envbar#27]
Would be good to have a class put into the body classes so if any theme modifications are needed, then can easily target the element with css.

e.g. a site already has a fixed navigation when the page scrolls (bootstrap affix). Since the Envbar is fixed also, then this sits over or under any other fixed menu bar, depending on what the z-index is. If there was a body class to indicate that the envbar was enabled, then a theme could cater for this.

**Comment by brendanheywood** [comment]
The body now has the 'local_envbar' class added
